### ISSUE TITLE
Hi, Could you please provide script for running MOT online?

### ISSUE THREAD

**Issue by hoangtuanvu** [yihongXU/deepMOT#1]

**Comment by yihongXU** [comment]
Hi, it is possible to run MOT online with our proposed method. But indeed, we didn't optimize the running speed during the implementation (the time-consuming birth and death process), so it is not time efficient.

You mentioned to provide a script for online MOT, can you tell what are the inputs and outputs you want in the script? I will do it when I have free time.

**Comment by yihongXU** [comment]
Knowing that in MOT17, you have 3 different types of detections for one ground truth (even the dataset copies 3 times the same gts.). Some you are actually training one gt several times. 
You can add in line 53:
'''
if "SDP" not in vname:
    continue
'''
