### ISSUE TITLE
the time to train？

### ISSUE THREAD

**Issue by wangaixue** [yihongXU/deepMOT#13]
Thank your for your work. It is first one to use SOT for MOT. I use 1080ti to train.  But It is too slow. It will cost one day for six epoch. Your paper say it will use 6 hours for 20 epoch in titanxp . Is there any change in code??

**Comment by yihongXU** [comment]
Hi, 6 hrs are for training DHN. When it is done, I took 72 hrs with Titan XP for training DeepMOT.


thanks,

**Comment by Ronales** [comment]
That's not first apply sot algorithm to MOT

**Comment by yihongXU** [comment]
No, it is not.
