### ISSUE TITLE
problem about plot_results.py

### ISSUE THREAD

**Issue by liubaorainbow** [yihongXU/deepMOT#21]
I have tried tracking_on_mot.py and train_mot.py. They both work fine.
But when i want to run plot_results.py, it only showed "loading parameters..." and no output.
![image](https://user-images.githubusercontent.com/39695322/69312982-4eb8f680-0c6b-11ea-86ea-53ea106dcc43.png)
What should i do? I only modified the curr_path in .py file.
![image](https://user-images.githubusercontent.com/39695322/69313040-7019e280-0c6b-11ea-8d9d-1b80fb78632e.png)

thanks a lot!

**Comment by yanfg1** [comment]
hello,did you solved this problem,i met the same issue too

**Comment by liubaorainbow** [comment]
not yet...

**Comment by leoliu37** [comment]
I modify the input parameters in 'plot_results.py', then it works.

**Comment by JOSHUAWENJZ** [comment]
@liubaorainbow @yanfg1 I have solved this problem. Modify "--data_root-default"like below.
![image](https://user-images.githubusercontent.com/50851416/70857229-6bbcae80-1f25-11ea-947b-7eeb5fdb4234.png)

**Comment by JOSHUAWENJZ** [comment]
@yihongXU Hi! Thank you for your share! And in line 144, I think it should be changed like below or your better modifition.
![image](https://user-images.githubusercontent.com/50851416/70857269-1d5bdf80-1f26-11ea-9b3f-0e20963570c8.png)

**Comment by JOSHUAWENJZ** [comment]
@yihongXU Hi! Thank you for your share! And in line 144, I think it should be changed like below or your better modifition.
![image](https://user-images.githubusercontent.com/50851416/70857277-47150680-1f26-11ea-97ba-393ce6a599b6.png)

**Comment by yihongXU** [comment]
@JOSHUAWENJZ  thank you so much, the code is corrected.
