### ISSUE TITLE
How to evaluate MOT17 test set performance if there are no groundtruth gt.txt files?

### ISSUE THREAD

**Issue by igygi** [yihongXU/deepMOT#24]
Hi,

May I know how you came up with the MOT17 test set metric results you provided in the readme? It seems that your evaluation.py code requires gt.txt files to generate these results. However, the gt.txt files are unavailable for the MOT17 test set. Thank you.

**Comment by JOSHUAWENJZ** [comment]
Hi, @igygi the ground truth of test sets in the MOT benchenmark is not piblic. If you want to get the results, you would upload your TEST.txt on MOT Challenge Networks [https://motchallenge.net/](url).

**Comment by igygi** [comment]
oh, okay. Thanks! @JOSHUAWENJZ
