### ISSUE TITLE
can you provide the training code of Deep Hungarian Network?

### ISSUE THREAD

**Issue by yjmlaile** [yihongXU/deepMOT#25]
Thank you very much for sharing your code. I am very interesting for this paper and i have some improvements to this model, i hope sincerely that you can share the training code of Deep Hungarian Network.

**Comment by amoskalev** [comment]
Hi, thanks for your work. I am also interested in training code for DHN.

**Comment by igygi** [comment]
Hi, same here. Would greatly appreciate if you can provide the training code for DHN. Thank you.

**Comment by superduduguan** [comment]
@yihongXU plz, we are all interested in your impressive work and want the training code for DHN.

**Comment by yihongXU** [comment]
Hi, the code is released.
