### ISSUE TITLE
How to train DHN?

### ISSUE THREAD

**Issue by igygi** [yihongXU/deepMOT#27]
Hi, 

How did you go about training DHN? From my understanding of the paper, you trained it as a standalone module (by itself, without the tracker and differentiable MOTA and MOTP, is that correct?)

Also, according to the paper, you used the focal loss as the supervisory signal for training the DHN. How did you compute for focal loss? 

Thank you.

**Comment by yihongXU** [comment]
Hi, the code for traninig DHN is uploaded. Thanks.
