### ISSUE TITLE
evaluation results lower than the results you shown in your paper

### ISSUE THREAD

**Issue by mimiao1991** [yihongXU/deepMOT#28]
I download your pretrained model and followed your instructions to test in MOT16 training dataset. The results I got like this:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/38508352/75250054-70012400-5812-11ea-8398-e6b87ba06e2d.png">
Have you test your model in other dataset?
Is the pretrained model the newest one?

**Comment by yihongXU** [comment]
Hi,
 MOT16 detections are quite noisy. For MOT by SOTs methods, as for MOT17, we passed the public detections to a classic FRCNN detector (as anchors) and clean them with the output detection scores.
 As you can see, we recently made a major update of the work, and the models and code, as well as the cleaned public detections that used in the newly updated paper, will be made publicly available in the following week.
