### ISSUE TITLE
difference about DAN and DHN

### ISSUE THREAD

**Issue by wangxianrui** [yihongXU/deepMOT#3]
notice that you use the DHN in training，
but use DAN in evaluate，
what is the difference, and how the DHN influence the tracking result ?

**Comment by yihongXU** [comment]
Hi, sorry about the notation issues.
DHN is only for training, which acts as a proxy to deliver gradient from MOT loss.
DAN is used as an appearance model, which can recover a lost track by comparing the appearances before and after the object is lost.
