### ISSUE TITLE
verison request

### ISSUE THREAD

**Issue by Kingaslan** [yihongXU/deepMOT#31]
Hi, Xu! Thanks for sharing your work.

Could you please offer the version of the python, pytroch and torchvison in this project? 
And also the verisons in Tracktor（from phil bergmann） : torch=0.3.1, torchvion=0.2.0. Is that compatible with deepmot?

Thanks

**Comment by yihongXU** [comment]
Hi,

the used version of pytorch is 0.4.1, torchvision=0.2.0.
