### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by JoanYu** [yihongXU/deepMOT#34]
The `requirements.txt` says that I should install Pytorch 1.3. But when I run `test_tracktor/experiments/scripts/tst_tracktor_private.py`, it said **ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.**, I tried to downgrade pytorch to 0.4.1 after asking on stackoverflow for help. But more errors raised!
I've commented out `from torch.utils.ffi import _wrap_function` in `test_tracktor/src/frcnn/frcnn/nms/_ext/nms/__init__.py`,and it raised a new error: ImportError: **test_tracktor/src/frcnn/frcnn/nms/_ext/nms/_nms.so: undefined symbol: state**.
I think it seem to be someting wrong on `_nms.so`, but I have no more solutions to fix this issue.

Best regards!

**Comment by yihongXU** [comment]
Hi,
Thank you trying our work.
You might be using the newer version of tracktor, you should go to the branch '2019ICCV' in the tracktor github and use Pytorch 0.4.1.

To make things easier, you could use the provided singularity image.

Thank you again.
