### ISSUE TITLE
Is it okay to use obsolete branch to reproduce your results?

### ISSUE THREAD

**Issue by songheony** [yihongXU/deepMOT#35]
I'd like to run your code on PyTorch 1.4.
But, the code in your master branch is only for PyTorch 0.4.1.
Is it possible to reproduce your results with obsolete branch?

**Comment by yihongXU** [comment]
Hi,
you could modify the master branch and use the newer version of Tracktor (pytorch 1.4) to adapt to Pytorch 1.4.

Thanks,

**Comment by songheony** [comment]
Does that mean you cannot reproduce your paper with the obsolete branch?
Since your master branch code uses customized fpn and frcnn, it is very difficult to modify it for PyTorch 1.4.
Could you give advice on how to modify the code?

**Comment by yihongXU** [comment]
Hi,

The part that is not compatible with Pytorch 1.4 is the FPN and FRCNN. So it's better to start adapting FPN, FRCNN in torchvision (>0.4) 
`
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.backbone_utils import resnet_fpn_backbone`
to the DeepMOT training. To avoid compilation, you can also replace customized NMS to torchvision.ops.NMS.

Actually, I have incomplete code for that, if you want I can send you the .py file and you can start with that, the work should be minimum then. You could leave your email.

Thanks,

**Comment by songheony** [comment]
Thank you very much for your help. 
I'm not sure if I can reproduce your tracker by modifying the code, but I'll try to do so.
Please send the file to the e-mail address below:
songheony@gmail.com

**Comment by yihongXU** [comment]
> .

sent. :)

**Comment by yihongXU** [comment]
@songheony  the files are sent.

Good luck,
