### ISSUE TITLE
Not able to launch singularity image

### ISSUE THREAD

**Issue by ayushrox** [yihongXU/deepMOT#38]
I am getting this error :

FATAL:   container creation failed: mount /proc/self/fd/5->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/5: failed to mount squashfs filesystem: invalid argument

Kindly give an example for this statement :

singularity shell --nv --bind ________:_________  tracker.sif

**Comment by yihongXU** [comment]
Hi, 

What does it mean by "--bind :_"? Could you try to run the image without "--bind" ?

**Comment by ayushrox** [comment]
I tried with : 

~/deepMOT$ singularity shell --nv ./SingularityImages/tracker.sif

but again the same error popped up, I also reinstalled Singularity but no luck.

**Comment by yihongXU** [comment]
Hi,

That's weird. I don't have the issue using singularity version 3.5.3. Could you try this? otherwise, you can build your own singularity image with the following recipe:
```
Bootstrap: docker
#From: pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
From: floydhub/pytorch:0.4.1-gpu.cuda9cudnn7-py3.40

%post
  # Reinstall most current tensorbaordX, something magic about pip...
  apt-get update && apt-get install -y --no-install-recommends \
           libgtk2.0-0 \
           libcanberra-gtk-module \
           build-essential \
           cmake \
           git \
           curl \
           vim \
           ca-certificates \
           libjpeg-dev \
           libpng-dev &&\
  rm -rf /var/lib/apt/lists/*
  pip install tensorboardx
  pip --no-cache-dir install motmetrics
  pip --no-cache-dir install matplotlib
```

**Comment by ayushrox** [comment]
I am new to linux environment, how can I implement this project as a jupyter notebook?
I see this as a wonderful opportunity to learn a state-of-the-art technology please guide me.
It would be really helpful as I could implement this on a better GPU from Google Colab.
