### ISSUE TITLE
why use DAN in inference instead of DHN?

### ISSUE THREAD

**Issue by wangxianrui** [yihongXU/deepMOT#4]
consider you have trained the SiamTPN + DHN, and why do't use the optimal assignment matrix to get the final result, but use the DAN that have not trained together?

**Comment by jjldr** [comment]
> consider you have trained the SiamTPN + DHN, and why do't use the optimal assignment matrix to get the final result, but use the DAN that have not trained together?

Have you solved the problem? I am also confuse about DHN and  DAN

**Comment by yihongXU** [comment]
Hi all, 
using DHN to do assignment during tracking is too strict. Detections are noisy and insufficient in many cases. So one-to-one assignment is too harsh for tracking, so we loose the constraint by allowing one-to-many assignment during tracking (test time). (but it should be for evaluating or training. Moreover, we use clean ground truth instead during training).
DHN and DAN are two different things, yes DAN is used to do assignment in the original paper, but here we use it as an appearance extractor, just for reactivating tracks, according to appearance similarities.

Yes, we can use a better (if exist) appearance model and/or refine the appearance model on MOT dataset. I am looking forward to having your pull requests for any possible improvements.

**Comment by Jacobew** [comment]
@yihongXU can you please point out the details of DAN in your paper? I can't find it anywhere. I am a little bit surprised that you do not use fixed DHN in inference like what DeepMOT does in training.
