### ISSUE TITLE
Cloning into 'deepmot'... Permission denied (publickey).

### ISSUE THREAD

**Issue by PollyBelova** [yihongXU/deepMOT#43]
user  command $ "git clone git@gitlab.inria.fr:yixu/deepmot.git"

**following error has been encountered:**

Cloning into 'deepmot'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by yihongXU** [comment]
Hi,

You need to register at gitlab.inria.fr before git clone. 

Best,
