### ISSUE TITLE
problem about  tracking

### ISSUE THREAD

**Issue by RemGao** [yihongXU/deepMOT#5]
Hi！Thanks for your decent work. I have a problem when I run tracking_on_mot.py as follow.Could you tell me what can I do for this problem.
![image](https://user-images.githubusercontent.com/12468586/60954505-af393e00-a331-11e9-8f5d-aa0224e7725a.png)

**Comment by yihongXU** [comment]
Hi, thanks for your feedbacks. I use OpenCV 4.1.0 and this version provides a default value:
```python
criteria=(1, 1, 2)
```
But I found an example, [https://www.programcreek.com/python/example/89338/cv2.findTransformECC](https://www.programcreek.com/python/example/89338/cv2.findTransformECC), which gives:
```python
criteria=((3, 5000, 1e-08)
```
You can simply define your criteria and put it to the function.
I didn't think deep on this parameter, and I am happy if you try both and give me some feedbacks.

Thanks in advance.

**Comment by RemGao** [comment]
Thank you for your kind answer. I have added the criteria as you suggestion but there is still mistake ‘required argument ‘inputMask’’. However, I annotate  the ECC function then I pass.

**Comment by chuan-jiang-828** [comment]
In stead of comment out ECC function, you can put inputMask = None, and gaussFiltSize = 1 and get it running.

**Comment by sourabhyadav** [comment]
Thanks, the last option worked for me.
