### ISSUE TITLE
Problem about track_on_mot.py

### ISSUE THREAD

**Issue by jjldr** [yihongXU/deepMOT#6]
Thank you for your sharing. However, in tracking_on_mot.py, your implementation of siameseRPN is not parallel, which lead to very slow inference time. Could you provide a parallel version. Thank you.

**Comment by yihongXU** [comment]
Hi, you are right. 
I did it in sequential way in order to let more people with limited GPU resources run the code. Current version needs around 2Gb of memory.

I will try to make a parallel version soon (hopefully this weekend). 

Thanks for pointing out the problem.
