### ISSUE TITLE
Hi thanks for your great job and share，i want to know can the project run on cpu only?

### ISSUE THREAD

**Issue by ubuntuyumiao** [yihongXU/deepMOT#7]

**Comment by chenjun2hao** [comment]
maybe you can set the parameter `--is_cuda` False

**Comment by yihongXU** [comment]
Hi, I've never tested on CPU since I would be too slow.

**Comment by ubuntuyumiao** [comment]
> Hi, I've never tested on CPU since I would be too slow.

thanks for your reply，after i changed your code and run on my laptop，It’s really too slow。
